runtime: python39

# You can specify automatic scaling, manual scaling, or basic scaling.
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic  # Default is automatic
  min_pending_latency: automatic  # Default is 30ms
  max_pending_latency: automatic  # Default is 30ms

# Environment variables that will be available to your application
env_variables:
  FLASK_ENV: "production"

# If your app listens to a port other than 8080, you must specify the port
# here. Google App Engine will route requests to this port.
entrypoint: gunicorn -b :$PORT main:app

# Handlers define how to respond to URL paths
handlers:
  # Serve all requests to this service
  - url: /.*
    script: auto